    title = "TOML 例子"

    [xaac]
    name = "xaac"
    dire = "xaac"
    cnName = "西安仲裁委员会"
    dob = 2020-12-09T07:32:00Z # 日期时间是一等公民.为什么不呢？

    [servers]

      # 您可以依照您的意愿缩进.使用空格或Tab.TOML不会在意.
      [servers.alpha]
      ip = "10.0.0.1"
      dc = "eqdc10"

      [servers.beta]
      ip = "10.0.0.2"
      dc = "eqdc10"

    [clients]
    data = [ ["gamma", "delta"], [1, 2] ]

    # 在数组里换行没有关系.
    hosts = [
      "alpha",
      "omega"
    ]